id: svim_brain
namespace: company.svim

tasks:
  - id: agent
    type: io.kestra.plugin.docker.Run
    containerImage: gmoreiradev/svim-agent:v0.0.79
    
    env:
      SVIM_MESSAGE: "{{ trigger.body.message }}"
      SVIM_USER_ID: "{{ trigger.body.user_id }}"
      SVIM_SESSION_ID: "{{ trigger.body.session_id }}"
      SVIM_CUSTOMER_PROFILE: "{{ trigger.body.customer_profile }}"
      SVIM_POLICIES_CONTEXT: "{{ trigger.body.policies_context }}"
      QDRANT_URL: "{{ kv('QDRANT_URL') }}"
      QDRANT_API_KEY: "{{ kv('QDRANT_API_KEY') }}"
      DATABASE_URL: "{{ kv('SVIM_DB_URL') }}"
      OPENAI_API_KEY: "{{ kv('SVIM_OPENAI_API_KEY') }}"
      X_API_TOKEN: "{{ kv('X_API_TOKEN_TRINKS') }}"
      ESTABELECIMENTO_ID: "{{ kv('ESTABELECIMENTO_ID') }}"
      URL_BASE: "{{ kv('URL_BASE') }}"
      
    commands:
      - "python"
      - "-m"
      - "agents.main"

  - id: output
    type: io.kestra.plugin.core.output.OutputValues
    values:
      response: "{{ outputs.agent.vars }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: svim-maria
    wait: true         
    returnOutputs: true