id: svim_brain
namespace: company.svim

inputs:
  - id: message
    type: STRING
  - id: user_id
    type: STRING
    defaults: anonymous
  - id: session_id
    type: STRING
    required: false
  - id: customer_profile
    type: JSON
    required: false
  - id: policies_context
    type: JSON
    required: false

tasks:
  - id: agent
    type: io.kestra.plugin.docker.Run
    containerImage: gmoreiradev/svim-agent:latest
    
    env:
      SVIM_MESSAGE: >-
        {{ default(trigger.body.message) }}

      SVIM_USER_ID: >-
        {{ default(trigger.body.user_id)
           | default('anonymous') }}

      SVIM_SESSION_ID: >-
        {{ default(trigger.body.session_id) }}

      SVIM_CUSTOMER_PROFILE: >-
        {{
          (default(trigger.body.customer_profile)
            | default({}))
          | toJson
        }}

      SVIM_POLICIES_CONTEXT: >-
        {{
          (default(trigger.body.policies_context)
            | default({}))
          | toJson
        }}

      QDRANT_URL: "{{ kv('QDRANT_URL') }}"
      QDRANT_API_KEY: "{{ kv('QDRANT_API_KEY') }}"
      DATABASE_URL: "{{ kv('SVIM_DB_URL') }}"
      OPENAI_API_KEY: "{{ kv('SVIM_OPENAI_API_KEY') }}"
      
    commands:
      - "python"
      - "-m"
      - "agents.main"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: svim-maria
    wait: true         
    returnOutputs: true