id: svim_brain
namespace: company.svim

tasks:
  - id: agent
    type: io.kestra.plugin.docker.Run
    containerImage: gmoreiradev/svim-agent:v0.0.4
    
    env:
      SVIM_MESSAGE: "{{ trigger.body.message }}"
      SVIM_USER_ID: "{{ trigger.body.user_id }}"
      SVIM_SESSION_ID: "{{ trigger.body.session_id }}"
      SVIM_CUSTOMER_PROFILE: "{{ trigger.body.customer_profile }}"
      SVIM_POLICIES_CONTEXT: "{{ trigger.body.policies_context }}"
      QDRANT_URL: "{{ kv('QDRANT_URL') }}"
      QDRANT_API_KEY: "{{ kv('QDRANT_API_KEY') }}"
      DATABASE_URL: "{{ kv('SVIM_DB_URL') }}"
      OPENAI_API_KEY: "{{ kv('SVIM_OPENAI_API_KEY') }}"
      
    commands:
      - "python"
      - "-m"
      - "agents.main"
    
    outputFiles:
    - "/tmp/output.json"

    varsRegex:
      response: "^(.*)$"

  - id: print_result
    type: io.kestra.plugin.core.log.Log
    message: "Resposta da Maria: {{ read(outputs.agent.outputFiles['/tmp/output.json']) }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: svim-maria
    wait: true         
    returnOutputs: true